// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOzgW56R-zGZzp2zD2yfMAAdmHq-SyTxY',
    appId: '1:900230553988:web:0ab1340a1112edfa57fdd1',
    messagingSenderId: '900230553988',
    projectId: 'true-link-a41f2',
    authDomain: 'true-link-a41f2.firebaseapp.com',
    storageBucket: 'true-link-a41f2.appspot.com',
    measurementId: 'G-FTDYRYYT6X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLMxYlklybod24dQWi5Z3jMxIrHt4ozG8',
    appId: '1:900230553988:android:5225864e2467fa3a57fdd1',
    messagingSenderId: '900230553988',
    projectId: 'true-link-a41f2',
    storageBucket: 'true-link-a41f2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCh3LULSANVRr4UbL3INCPbNX_ML5rdymk',
    appId: '1:900230553988:ios:d0b3120ec74619a957fdd1',
    messagingSenderId: '900230553988',
    projectId: 'true-link-a41f2',
    storageBucket: 'true-link-a41f2.appspot.com',
    iosBundleId: 'com.example.trueLink',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCh3LULSANVRr4UbL3INCPbNX_ML5rdymk',
    appId: '1:900230553988:ios:d0b3120ec74619a957fdd1',
    messagingSenderId: '900230553988',
    projectId: 'true-link-a41f2',
    storageBucket: 'true-link-a41f2.appspot.com',
    iosBundleId: 'com.example.trueLink',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDOzgW56R-zGZzp2zD2yfMAAdmHq-SyTxY',
    appId: '1:900230553988:web:afdf684ef4514ae457fdd1',
    messagingSenderId: '900230553988',
    projectId: 'true-link-a41f2',
    authDomain: 'true-link-a41f2.firebaseapp.com',
    storageBucket: 'true-link-a41f2.appspot.com',
    measurementId: 'G-P788XZ1KT5',
  );

}